# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/npcosine',
                'doc_host': 'https://rafribeiro.github.io',
                'git_url': 'https://github.com/rafribeiro/npcosine',
                'lib_path': 'npcosine'},
  'syms': {'npcosine.core': {'npcosine.core.foo': ('core.html#foo', 'npcosine/core.py')}}}
